### ISSUE TITLE
Redmine version 4.0.2 support

### ISSUE THREAD

**Issue by ECOWOOD** [devopskube/redmine_openid_connect#21]
My environment is Redmine version 4.0.2.stable. We would like support by all means because we want to do SSO by OpenID Connect.

```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ApplicationController:Class
Did you mean?  alias_method
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/lib/redmine_openid_connect/application_controller_patch.rb:7:in `block in included'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/lib/redmine_openid_connect/application_controller_patch.rb:6:in `class_eval'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/lib/redmine_openid_connect/application_controller_patch.rb:6:in `included'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/init.rb:18:in `include'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/init.rb:18:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by SIkebe** [comment]
Dup of #19?
