### ISSUE TITLE
internal server error - NoMethodError (undefined method `+' for nil:NilClass)...authorization_url

### ISSUE THREAD

**Issue by fwi27** [devopskube/redmine_openid_connect#5]
Hello

I have some trouble making the plugin work. I have the following error :

```
Processing by AccountController#oic_login as HTML
   (0.9ms)  SELECT MAX("settings"."updated_on") FROM "settings"
  AnonymousUser Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('AnonymousUser')  ORDER BY "users"."id" ASC LIMIT 1
  Current user: anonymous
   (0.4ms)  BEGIN
  SQL (0.6ms)  INSERT INTO "oic_sessions" ("created_at", "updated_at", "state", "nonce") VALUES ($1, $2, $3, $4) RETURNING "id"  [["created_at", "2017-12-15 20:56:16.409099"], ["updated_at", "2017-12-15 20:56:16.409099"], ["state", "899bd2a7-49e6-4ac0-bfc7-a6f33e64e462"], ["nonce", "d4205b19-059c-43ae-887f-0398a8533296"]]
   (2.5ms)  COMMIT
Completed 500 Internal Server Error in 14ms (ActiveRecord: 5.3ms)

NoMethodError (undefined method `+' for nil:NilClass):
  plugins/redmine_openid_connect/app/models/oic_session.rb:153:in `authorization_url'
  plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:61:in `oic_login'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

I use a local Keycloak OIDC provider and I provided this URL in the plugin configuration page :

![redmine_openidc_plugin](https://user-images.githubusercontent.com/16590230/34058506-8d7f67d0-e1db-11e7-8b98-0609c99f5f83.png)

Any idea ?

**Comment by avanvucht** [comment]
The problem here is that this plugin is expecting to find a 'authorization_url' in Keycloak's OpenID Connect 'well known configuration' endpoint, but Keycloak has it as 'authorization_endpoint'
You can view your local Keycloak's configuration at https://{keycloak server}/auth/realms/{realm}/.well-known/openid-configuration

Here's a sample for my Keycloak 3.4 openid-configuration
{
  "issuer": "https://{keycloak server}/auth/realms/master",
  "authorization_endpoint": "https://{keycloak server}/auth/realms/master/protocol/openid-connect/auth",
  "token_endpoint": "https://{keycloak server}/auth/realms/master/protocol/openid-connect/token",
  "token_introspection_endpoint": "https://{keycloak server}/auth/realms/master/protocol/openid-connect/token/introspect",
  "userinfo_endpoint": "https://{keycloak server}/auth/realms/master/protocol/openid-connect/userinfo",
  "end_session_endpoint": "https://{keycloak server}/auth/realms/master/protocol/openid-connect/logout",
... etc }

I think Keycloak's got it right - it should be authorization_endpoint, not authorization_url. See https://openid.net/specs/openid-connect-discovery-1_0.html - I will have to update the plugin to use these instead

**Comment by avanvucht** [comment]
I was getting this error too until I restarted the redmine server. So it looks like that after configuring the OpenID server settings, the redmine server needs to be restarted.

**Comment by jcmcken** [comment]
I'm hitting this error as well. I've attempted to restart, same result.

**Comment by jcmcken** [comment]
Turns out I was just using the wrong URL. The URL needs to support the ``/.well-known/openid-configuration`` path, which you can test in your browser. So really, the bug is that the plugin throws an unhandled exception when the URL is wrong rather than error appropriately.

**Comment by uaqben** [comment]
@jcmcken - I have the same error; even though I have the `/.well-known/openid-configuration` URL specified.

**Comment by jcmcken** [comment]
@uaqben If your OIDC config URL is https://example.com/.well-known/openid-configuration, the URL should be set to https://example.com (at least that's what worked for me)

**Comment by marty-macfly** [comment]
I'm doing the same setup with keycloak and I've got the following error did you change something else on Keycloak client configuration ?

```
ActiveRecord::StatementInvalid (Mysql2::Error: Data too long for column 'code' at row 1: UPDATE `oic_sessions` SET `code` = 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..eZz6h3o-1-kpQvlprt45_g.Ppw-ZHpAnFn0jsvpbroB1Po6VtT1OWz8VQ35m5A__nnfr0yVUbUt-L6qmRV2XKKlc7k5o6DxuZsTSQQJEPTNh33kzovRLJvIr2L56DVu-R3DER3NPC5R3O1bhKywdUOwaWJ1T0tpopwWeSNERRtIWooEFMUfokniuJUmFdivt4w7ji4d0OqtifCVPojMre7aiv-SoEf2-LW84XPAl5Y9wuktuE9_hn0IpwX7WCeCNtI3jtBNwC4pEJTU9rJUBw69.st1QO8eEjBrV3AzsXUDIPQ', `session_state` = '82a558cb-84ad-4586-a692-166c9aed5e3e', 
```

**Comment by brunojcm** [comment]
I had to use the URL **without** a trailing `/` as well, otherwise, I would still get an error.

**Comment by C0rn3j** [comment]
For posterity - 
Since this is a Keycloak thread, you probably want to use the `openid` Scope in the plugin settings, and you want to restart Redmine after every change just to be sure you're not hitting a caching issue.

**Comment by Born2Bake** [comment]
Unfortunately, for some reason it's still failing for me with:

```
F, [2021-05-27T11:31:33.471675 #1] FATAL -- :
F, [2021-05-27T11:31:33.471740 #1] FATAL -- : NoMethodError (undefined method `+' for nil:NilClass):
F, [2021-05-27T11:31:33.471786 #1] FATAL -- :
F, [2021-05-27T11:31:33.471826 #1] FATAL -- : plugins/redmine_openid_connect/app/models/oic_session.rb:187:in `authorization_url'
plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:49:in `oic_login'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

Whatever configuration I use in plugins/openid section, always getting an error - Internal error url.com/oic/login

**Comment by miguemc** [comment]
Same error with Redmine 4.2.3

**Comment by lmarie23** [comment]
Any news on this issue ? 
I am still encountering it

**Comment by MPavleski** [comment]
Hello, I think I encountered this issue. To resolve it, I added **openid** scope explicitly in "
OpenID Connect scopes (comma-separated)" settings , in addition to **profile** and **email** scopes. Please see the screenshot.

![Screenshot 2023-01-26 074418](https://user-images.githubusercontent.com/2526975/214773818-a90feca0-0cf7-4be1-9adc-a963b844c93b.png)

**Comment by guoanhao** [comment]
> 你好，我想我遇到了这个问题。为了解决这个问题，我在“OpenID Connect 范围（逗号分隔）”设置中明确添加了**openid**范围 ，以及**配置文件**和**电子邮件**范围。请看截图。
> 
> ![截图 2023-01-26 074418](https://user-images.githubusercontent.com/2526975/214773818-a90feca0-0cf7-4be1-9adc-a963b844c93b.png)

hi，Can your redmine+keycloak work normally，My redmine configuration is the same as yours, but I can't log in，The configuration of keycloak refers to：http://devopsku.be/setup/redmine-keycloak/

redmine 4.2.8  keycloak 18.0.2
Can you help me，thank you！
