### ISSUE TITLE
Login fails with PG::ProgramLimitExceeded

### ISSUE THREAD

**Issue by fujexo** [devopskube/redmine_openid_connect#52]
```
Completed 500 Internal Server Error in 1448ms (ActiveRecord: 12.7ms)

ActiveRecord::StatementInvalid (PG::ProgramLimitExceeded: ERROR:  index row size 2752 exceeds maximum 2712 for index "index_oic_sessions_on_access_token"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
: UPDATE "oic_sessions" SET "access_token" = $1, "refresh_token" = $2, "expires_at" = $3, "updated_at" = $4 WHERE "oic_sessions"."id" = $5):

plugins/redmine_openid_connect/app/models/oic_session.rb:82:in `get_access_token!'
plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:82:in `oic_local_login'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

Any ideas how to fix this?

**Comment by winged** [comment]
I think the indexes on `access_token`, `refresh_token` and `id_token` are not needed, as all the lookups  on `oic_sessions` seem to go via primary key.
