### ISSUE TITLE
Server error when sending an access token which is not JWT

### ISSUE THREAD

**Issue by coudot** [devopskube/redmine_openid_connect#54]
I use your plugin with LemonLDAP::NG.

Here is the error I got:
```
Completed 500 Internal Server Error in 273ms (ActiveRecord: 22.4ms)
  
NoMethodError (undefined method `unpack1' for nil:NilClass):
  
plugins/redmine_openid_connect/app/models/oic_session.rb:178:in `user'
plugins/redmine_openid_connect/app/models/oic_session.rb:163:in `admin?'
plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:143:in `oic_local_login'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

This is thrown by this code: https://github.com/devopskube/redmine_openid_connect/blob/master/app/models/oic_session.rb#L178

An access token can be a JWT but it is not mandatory.

I think we should first try id_token to get values, or only tryaccess_token if it is a JWT.

**Comment by artlog** [comment]
As of today this bug is still there, it was introduced with 'adapt to new keycloak behaviour (#45)' commit 2f2cc91f2e331f31ebe20420c1ff461d036380bb

fixing is quite obvious : undo this change...
