### ISSUE TITLE
Unable to create new local redmine user after successful OIDC login

### ISSUE THREAD

**Issue by pradintegrsso** [devopskube/redmine_openid_connect#61]
I18n::MissingInterpolationArgument (missing interpolation argument :value in "Could not create the user %{value}: " ({:count=>nil} given)):

lib/redmine/i18n.rb:36:in `l'
plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:133:in `oic_local_login'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
Started GET "/oic/local_login?code=-RoKZNtTN2_fz3J-XW08M_b_xU433M-nKrJwNRumuC4&state=0b49e273-5842-462e-9cf5-116a52d757ca" for 146.107.124.99 at 2022-02-02 13:18:45 +0100
Processing by AccountController#oic_local_login as HTML
  Parameters: {"code"=>"-RoKZNtTN2_fz3J-XW08aeafavdzObadfUDC-nKrJwNRumuC4", "state"=>"0b49e273-5842-345f-9cf5-116a52d757ca"}
  Current user: anonymous
Completed 500 Internal Server Error in 801ms (ActiveRecord: 7.2ms)
![redmine-error](https://user-images.githubusercontent.com/88323264/152161575-ebe6677b-9925-468a-9a2b-3ddb5f52b856.png)

**Comment by Sik1a** [comment]
can you provide the config of your plugins
