### ISSUE TITLE
Openid connect redmine error on redirects

### ISSUE THREAD

**Issue by jgprouty** [devopskube/redmine_openid_connect#65]
I installed the openid connect plugin
when I click on sso login  I get
http://10.249.32.22:3000/oic/login?utf8=%E2%9C%93&back_url=%2F&login-openid=Login+with+SSO
Page not found

I have verified my redirect url 

I am doing this on ubuntu 22.04
redmine 5.0.1

, [2022-06-01T19:10:32.449572 #1245]  INFO -- : [2666f2ab-b803-4b2a-ae90-a1a9febc040e] Started GET "/oic/login?utf8=%E2%9C%93&back_url=%2F&login-openid=Login+with+SSO" for 10.249.8.2 at 2022-06-01 19:10:32 +0000
F, [2022-06-01T19:10:32.454154 #1245] FATAL -- : [2666f2ab-b803-4b2a-ae90-a1a9febc040e]
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] AbstractController::ActionNotFound (The action 'oic_login' could not be found for AccountController
Did you mean?  require_login
               check_if_login_required
               autologin_cookie_name
               try_to_autologin):
[2666f2ab-b803-4b2a-ae90-a1a9febc040e]
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/abstract_controller/base.rb:160:in `process'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionview (6.1.6) lib/action_view/rendering.rb:39:in `process'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_controller/metal.rb:190:in `dispatch'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_controller/metal.rb:254:in `dispatch'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `each'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `serve'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/tempfile_reaper.rb:15:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/etag.rb:27:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/conditional_get.rb:27:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/head.rb:12:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/session/abstract/id.rb:266:in `context'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/session/abstract/id.rb:260:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] activesupport (6.1.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] railties (6.1.6) lib/rails/rack/logger.rb:37:in `call_app'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] railties (6.1.6) lib/rails/rack/logger.rb:26:in `block in call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] activesupport (6.1.6) lib/active_support/tagged_logging.rb:37:in `tagged'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `tagged'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] railties (6.1.6) lib/rails/rack/logger.rb:26:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/method_override.rb:24:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/runtime.rb:22:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] activesupport (6.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/static.rb:24:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/sendfile.rb:110:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] rack (2.2.3.1) lib/rack/content_length.rb:17:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] actionpack (6.1.6) lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] railties (6.1.6) lib/rails/engine.rb:539:in `call'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[2666f2ab-b803-4b2a-ae90-a1a9febc040e] /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by joseEkcit** [comment]
Hi! There are some issues with this plugin in the latest version of Redmine and Rails.
I created a fork with the minimun changes for my configuration to work, maybe that helps:
https://github.com/joseEkcit/redmine_openid_connect
