### ISSUE TITLE
Internal error / JSON::ParserError (859: unexpected token at ''):

### ISSUE THREAD

**Issue by silviu001** [devopskube/redmine_openid_connect#76]
Hello,

I am running Redmine 5.0.4.stable (docker hub official image). I have installed redmine_openid_connect version 0.9.4 and configured a Keycloak instance for OpenID Connect SSO. I have checked the Keycloak JWT generated token and it contains every attributed described in the README. After I authenticate my user I get `Internal error` and redmine logging (debug) outputs:

`
I, [2023-01-17T09:47:48.703454 #1]  INFO -- : Completed 500 Internal Server Error in 30ms (ActiveRecord: 2.9ms | Allocations: 2442)
F, [2023-01-17T09:47:48.704098 #1] FATAL -- :
JSON::ParserError (859: unexpected token at ''):

plugins/redmine_openid_connect/app/models/oic_session.rb:125:in `get_user_info!'
plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:83:in `oic_local_login'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
` 

What can I do further to overcome this issue? If necessary I can provide extra information if necessary. 

Thanks,
Silviu.

My full environment:

`
  Environment:
  Redmine version                5.0.4.stable
  Ruby version                   3.1.3-p185 (2022-11-24) [x86_64-linux]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_openid_connect         0.9.4
`

**Comment by Sik1a** [comment]
can you provide me the configuration on the plugin
