### ISSUE TITLE
LDAP fields with Turkish characters generate JSON errors

### ISSUE THREAD

**Issue by osmanyozgatlioglu** [devopskube/redmine_openid_connect#90]
My standart setup is;

> Redmine 5.0.6.stable
> Environment:
>   Redmine version                5.0.6.stable
>   Ruby version                   3.1.4-p223 (2023-03-30) [x86_64-linux]
>   Rails version                  6.1.7.6
>   Environment                    production
>   Database adapter               PostgreSQL
>   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
>   Mailer delivery                smtp
> Redmine settings:
>   Redmine theme                  Default
> SCM:
>   Git                            2.39.3
>   Filesystem                     
> Redmine plugins:
>   redmine_openid_connect         0.9.4

Redmine Openid Connect plugin configuration;

> OpenID Connect Configuration Enabled
> Client ID redmineclient
> OpenID Connect server url https://keycloak.mezitli.local/realms/redminerealm
> Client Secret ••••••••••••••••••••••••••••••••
> OpenID Connect scopes (comma-separated) openid
> Authorized group (blank if all users are authorized)
> Admins group (members of this group are treated as admin) admin
> How often to retrieve openid configuration (default 1 day)
> Disable Ssl Validation Selected
> Login Selector
> Create user if not exists Selected
> Users from the following auth sources will be required to login with SSO

At Keycloak, I have LDAP user federation and map givenName as  firstName (Osman) and sn as lastName (Yozgatlıoğlu), (ldap representation is sn:: WW96Z2F0bMSxb8SfbHU=)

When I try to login Redmine, following log generated;

> I, [2023-11-23T10:32:31.801419 #11303]  INFO -- : [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80] Started GET "/oic/local_login?state=e36e1320-2f8f-415d-af7e-d42bf4ef2d79&session_state=1876cf6a-6205-44d7-80c4-44abb6616e99&code=bc2ca79e-6845-408e-9912-4f2b3784d6e4.1876cf6a-6205-44d7-80c4-44abb6616e99.3fd2d239-d3f3-421c-be94-7f2872e31129" for 192.168.1.50 at 2023-11-23 10:32:31 +0300
> I, [2023-11-23T10:32:31.802501 #11303]  INFO -- : [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80] Processing by AccountController#oic_local_login as HTML
> I, [2023-11-23T10:32:31.802728 #11303]  INFO -- : [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80]   Parameters: {"state"=>"e36e1320-2f8f-415d-af7e-d42bf4ef2d79", "session_state"=>"1876cf6a-6205-44d7-80c4-44abb6616e99", "code"=>"bc2ca79e-6845-408e-9912-4f2b3784d6e4.1876cf6a-6205-44d7-80c4-44abb6616e99.3fd2d239-d3f3-421c-be94-7f2872e31129"}
> I, [2023-11-23T10:32:31.810147 #11303]  INFO -- : [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80]   Current user: anonymous
> I, [2023-11-23T10:32:31.815778 #11303]  INFO -- : [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80] Completed 500 Internal Server Error in 13ms (ActiveRecord: 3.4ms | Allocations: 4328)
> F, [2023-11-23T10:32:31.816626 #11303] FATAL -- : [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80]   
> [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80] JSON::ParserError (859: unexpected token at '{"exp":1700718146,"iat":1700717846,"auth_time":1700717846,"jti":"da731fa1-6e34-49e2-8109-75ab91ef9527","iss":"https://keycloak.mezitli.local/realms/redminerealm","aud":"redmineclient","sub":"f:b88a00eb-702a-41e6-b4e2-12e36cab75f9:osman3.yozgatlioglu","typ":"ID","azp":"redmineclient","nonce":"63baad13-df0b-4a9c-bf65-4df6af49147c","session_state":"da390142-92ff-475c-8515-e94a99420dd6","at_hash":"oNgyw_XTDaNBgdS2bSroKw","acr":"1","sid":"da390142-92ff-475c-8515-e94a99420dd6","email_verified":true,"name":"Osman Yozgatlıoğlu","preferred_username":"osman3.yozgatlioglu","given_name":"Osman","family_name":"Yozgatlıa'�H�[XZ�����X[��[ޙ�]�[��P�\�X^�[�[K���K���'):
> [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80]   
> [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80] plugins/redmine_openid_connect/app/models/oic_session.rb:101:in `parse_token'
> [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80] plugins/redmine_openid_connect/app/models/oic_session.rb:106:in `claims'
> [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80] plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:75:in `oic_local_login'
> [7164e47b-8eca-44d8-8c9c-2ec5a52f7d80] lib/redmine/sudo_mode.rb:61:in `sudo_mode'

Browser shows following error;
> Internal error
> An error occurred on the page you were trying to access.
> If you continue to experience problems please contact your Redmine administrator for assistance.
> If you are the Redmine administrator, check your log files for details about the error.

Also no new user created. If I try any user with only English characters, I can login successfully and user created at Redmine.
If you need any other info, I have test setup ready.

Regards,

**Comment by moon-jun** [comment]
#100 
I found a solution to this read this and apply it!




fix: JWT Token JSON Parsing Error with non-ASCII characters

Purpose:

JWT tokens use Base64 URL encoding. Therefore, before performing Base64 decoding, URL-safe characters ('-', '_') must be replaced with standard Base64 characters ('+', '/').

The JWT payload (which may include non-ASCII characters such as Korean or Turkish) is a JSON string encoded in UTF-8. Thus, the byte array obtained after Base64 decoding should be converted into a UTF-8 string.

Finally, parse the UTF-8 string as JSON and return the resulting JavaScript object.
